package com.tal.hebrewdino.ui.domain

import androidx.annotation.DrawableRes
import com.tal.hebrewdino.R

/** Raster lesson art in `res/drawable-nodpi/lesson_pic_*.png`. */
object RasterLessonPicDrawables {
    val tileDrawables: Set<Int> =
        setOf(
            // Season 1 Chapter 1 (א ב ד ל מ)
            R.drawable.lesson_pic_ish,
            R.drawable.lesson_pic_aryeh,
            R.drawable.lesson_pic_avatiach,
            R.drawable.lesson_pic_car,
            R.drawable.lesson_pic_arnav,
            R.drawable.lesson_pic_bait,
            R.drawable.lesson_pic_balloon,
            R.drawable.lesson_pic_barvaz,
            R.drawable.lesson_pic_dag,
            R.drawable.lesson_pic_delet,
            R.drawable.lesson_pic_dachlil,
            R.drawable.lesson_pic_dvash,
            R.drawable.lesson_pic_degel,
            R.drawable.lesson_pic_lechem,
            R.drawable.lesson_pic_lev,
            R.drawable.lesson_pic_limon,
            R.drawable.lesson_pic_machbat,
            R.drawable.lesson_pic_medusa,
            R.drawable.lesson_pic_mitah,
            R.drawable.lesson_pic_motzetz,
            R.drawable.lesson_pic_meil,
            // Chapters 2 / 4 / 5 (and Ch6 review) — raster lesson art
            R.drawable.lesson_pic_gamal,
            R.drawable.lesson_pic_glida,
            R.drawable.lesson_pic_gader,
            R.drawable.lesson_pic_girafa,
            R.drawable.lesson_pic_gag,
            R.drawable.lesson_pic_har,
            R.drawable.lesson_pic_haftaa,
            R.drawable.lesson_pic_hipopotam,
            R.drawable.lesson_pic_vered,
            R.drawable.lesson_pic_wafel,
            R.drawable.lesson_pic_vilon,
            R.drawable.lesson_pic_rosh,
            R.drawable.lesson_pic_rakevet,
            R.drawable.lesson_pic_regel,
            R.drawable.lesson_pic_ramzor,
            R.drawable.lesson_pic_shemesh,
            R.drawable.lesson_pic_shulchan,
            R.drawable.lesson_pic_shinayim,
            R.drawable.lesson_pic_shaon,
            R.drawable.lesson_pic_chatul,
            R.drawable.lesson_pic_chalav,
            R.drawable.lesson_pic_chalon,
            R.drawable.lesson_pic_chultza,
            R.drawable.lesson_pic_tost,
            R.drawable.lesson_pic_telefon,
            R.drawable.lesson_pic_tigris,
            R.drawable.lesson_pic_kise,
            R.drawable.lesson_pic_kelev,
            R.drawable.lesson_pic_kadur,
            R.drawable.lesson_pic_perach,
            R.drawable.lesson_pic_pil,
            R.drawable.lesson_pic_pilpel,
            R.drawable.lesson_pic_parpar,
            R.drawable.lesson_pic_tapuach,
            R.drawable.lesson_pic_tik,
            R.drawable.lesson_pic_tinok,
            R.drawable.lesson_pic_tof,
            R.drawable.lesson_pic_nemala,
            R.drawable.lesson_pic_ner,
            R.drawable.lesson_pic_naalayim,
            R.drawable.lesson_pic_nachash,
            R.drawable.lesson_pic_tzipor,
            R.drawable.lesson_pic_tzav,
            R.drawable.lesson_pic_tzfardea,
            R.drawable.lesson_pic_tzalachat,
            R.drawable.lesson_pic_kof,
            R.drawable.lesson_pic_kubia,
            R.drawable.lesson_pic_katar,
            // Season 2 Chapter 1
            R.drawable.lesson_pic_zebra,
            R.drawable.lesson_pic_zikit,
            R.drawable.lesson_pic_zakhal,
            R.drawable.lesson_pic_zer,
            R.drawable.lesson_pic_zanav,
            R.drawable.lesson_pic_yeled,
            R.drawable.lesson_pic_yad,
            R.drawable.lesson_pic_yona,
            R.drawable.lesson_pic_yareach,
            R.drawable.lesson_pic_yanshuf,
            R.drawable.lesson_pic_sus,
            R.drawable.lesson_pic_sira,
            R.drawable.lesson_pic_sukariya,
            R.drawable.lesson_pic_sefer,
            R.drawable.lesson_pic_sartan,
            R.drawable.lesson_pic_ayin,
            R.drawable.lesson_pic_agvania,
            R.drawable.lesson_pic_akbar,
            R.drawable.lesson_pic_uga,
            R.drawable.lesson_pic_etz,
            R.drawable.lesson_pic_aleh,
            R.drawable.lesson_pic_akavish,
        )

    fun isPngTile(@DrawableRes drawableRes: Int): Boolean = drawableRes in tileDrawables
}
