package com.tal.hebrewdino.ui.domain

object WordChallengeRepository {
    val oddOneOutHebrew: List<WordChallenge> =
        listOf(
            WordChallenge(
                id = "odd_001",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ח\".",
                options = listOf("חמור", "חזיר", "חלב", "מספריים"),
                correctOption = "מספריים",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_002",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"כ\".",
                options = listOf("כדור", "כיסא", "כפית", "תינוק"),
                correctOption = "תינוק",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_003",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ב\".",
                options = listOf("בלון", "בובה", "בית", "דג"),
                correctOption = "דג",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_004",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ד\".",
                options = listOf("דג", "דלת", "דבש", "חתול"),
                correctOption = "חתול",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_005",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"מ\".",
                options = listOf("מכונית", "מיטה", "מלפפון", "סוס"),
                correctOption = "סוס",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_006",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ס\".",
                options = listOf("סוכר", "סנדל", "סוס", "כדור"),
                correctOption = "כדור",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_007",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ש\".",
                options = listOf("שמש", "שוקו", "שולחן", "אבטיח"),
                correctOption = "אבטיח",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_008",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ר\".",
                options = listOf("רגל", "רכבת", "רימון", "בקבוק"),
                correctOption = "בקבוק",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_009",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"א\".",
                options = listOf("אוטו", "אבא", "אוכל", "מדורה"),
                correctOption = "מדורה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_010",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ל\".",
                options = listOf("לב", "לימון", "לחם", "מטרייה"),
                correctOption = "מטרייה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_011",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"פ\".",
                options = listOf("פרפר", "פיל", "פיצה", "גדר"),
                correctOption = "גדר",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_012",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"נ\".",
                options = listOf("נמלה", "נעל", "נר", "גלידה"),
                correctOption = "גלידה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_013",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ת\".",
                options = listOf("תוף", "תפוח", "תינוק", "כורסה"),
                correctOption = "כורסה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_014",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ק\".",
                options = listOf("קוף", "קיץ", "קופסה", "ממתק"),
                correctOption = "ממתק",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_015",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ג\".",
                options = listOf("גזר", "גדר", "גרב", "חלון"),
                correctOption = "חלון",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
        )

    val rhymesHebrew: List<WordChallenge> =
        listOf(
            WordChallenge(
                id = "rhyme_001",
                questionText = "בלון",
                options = listOf("חלון", "חתול", "כיסא", "סוס"),
                correctOption = "חלון",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_002",
                questionText = "דבש",
                options = listOf("יבש", "כובע", "רכבת", "לב"),
                correctOption = "יבש",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_003",
                questionText = "בית",
                options = listOf("זית", "אוטו", "דלת", "ספר"),
                correctOption = "זית",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_004",
                questionText = "סוס",
                options = listOf("כוס", "גדר", "תפוח", "כיסא"),
                correctOption = "כוס",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_005",
                questionText = "פרח",
                options = listOf("ירח", "כדור", "חלון", "סנדל"),
                correctOption = "ירח",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_006",
                questionText = "דג",
                options = listOf("חג", "בובה", "גזר", "כובע"),
                correctOption = "חג",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_007",
                questionText = "לחם",
                options = listOf("ים", "ספר", "דג", "לימון"),
                correctOption = "ים",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_008",
                questionText = "תוף",
                options = listOf("סוף", "תפוח", "נעל", "רכבת"),
                correctOption = "סוף",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_009",
                questionText = "גדר",
                options = listOf("חדר", "כוס", "בובה", "תפוח"),
                correctOption = "חדר",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_010",
                questionText = "קוף",
                options = listOf("סוף", "דג", "חלון", "סוס"),
                correctOption = "סוף",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_011",
                questionText = "רימון",
                options = listOf("לימון", "תפוח", "כוס", "מיטה"),
                correctOption = "לימון",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_012",
                questionText = "פרפר",
                options = listOf("ספר", "חלב", "חדר", "נעל"),
                correctOption = "ספר",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_013",
                questionText = "כדור",
                options = listOf("סידור", "נר", "דג", "חלון"),
                correctOption = "סידור",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_014",
                questionText = "תינוק",
                options = listOf("חילוק", "חלב", "קופסה", "דג"),
                correctOption = "חילוק",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_015",
                questionText = "חלון",
                options = listOf("בלון", "כובע", "תפוח", "מיטה"),
                correctOption = "בלון",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
        )
}
