package com.tal.hebrewdino.ui.domain

object WordChallengeRepository {
    val oddOneOutHebrew: List<WordChallenge> =
        listOf(
            WordChallenge(
                id = "odd_001",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ח\".",
                options = listOf("חמור", "חזיר", "חלב", "מספריים"),
                correctOption = "מספריים",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_002",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"כ\".",
                options = listOf("כדור", "כיסא", "כפית", "תינוק"),
                correctOption = "תינוק",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_003",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ב\".",
                options = listOf("בלון", "בובה", "בית", "דג"),
                correctOption = "דג",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_004",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ד\".",
                options = listOf("דג", "דלת", "דבש", "חתול"),
                correctOption = "חתול",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_005",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"מ\".",
                options = listOf("מכונית", "מיטה", "מלפפון", "סוס"),
                correctOption = "סוס",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_006",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ס\".",
                options = listOf("סוכר", "סנדל", "סוס", "כדור"),
                correctOption = "כדור",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_007",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ש\".",
                options = listOf("שמש", "שוקו", "שולחן", "אבטיח"),
                correctOption = "אבטיח",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_008",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ר\".",
                options = listOf("רגל", "רכבת", "רימון", "בקבוק"),
                correctOption = "בקבוק",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_009",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"א\".",
                options = listOf("אוטו", "אבא", "אוכל", "מדורה"),
                correctOption = "מדורה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_010",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ל\".",
                options = listOf("לב", "לימון", "לחם", "מטרייה"),
                correctOption = "מטרייה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_011",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"פ\".",
                options = listOf("פרפר", "פיל", "פיצה", "גדר"),
                correctOption = "גדר",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_012",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"נ\".",
                options = listOf("נמלה", "נעל", "נר", "גלידה"),
                correctOption = "גלידה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_013",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ת\".",
                options = listOf("תוף", "תפוח", "תינוק", "כורסה"),
                correctOption = "כורסה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_014",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ק\".",
                options = listOf("קוף", "קיץ", "קופסה", "ממתק"),
                correctOption = "ממתק",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_015",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ג\".",
                options = listOf("גזר", "גדר", "גרב", "חלון"),
                correctOption = "חלון",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
        )

    val rhymesHebrew: List<WordChallenge> =
        listOf(
            WordChallenge(
                id = "rhyme_001",
                questionText = "איזה זוג מתחרז?",
                options = listOf("בלון / חלון", "כיסא / כפית", "חתול / סוס", "דג / מיטה"),
                correctOption = "בלון / חלון",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_002",
                questionText = "איזה זוג מתחרז?",
                options = listOf("דבש / יבש", "פרפר / כובע", "רכבת / מלפפון", "לב / דג"),
                correctOption = "דבש / יבש",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_003",
                questionText = "איזה זוג מתחרז?",
                options = listOf("בית / זית", "מיטה / אוטו", "נעל / דלת", "כדור / ספר"),
                correctOption = "בית / זית",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_004",
                questionText = "איזה זוג מתחרז?",
                options = listOf("סוס / כוס", "שמש / גדר", "נר / תפוח", "אבטיח / כיסא"),
                correctOption = "סוס / כוס",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_005",
                questionText = "איזה זוג מתחרז?",
                options = listOf("חתול / כדור", "פרח / ירח", "אוכל / חלון", "כפית / סנדל"),
                correctOption = "פרח / ירח",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_006",
                questionText = "איזה זוג מתחרז?",
                options = listOf("דג / חג", "מיטה / בובה", "גרב / גזר", "חלב / כובע"),
                correctOption = "דג / חג",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_007",
                questionText = "איזה זוג מתחרז?",
                options = listOf("נר / ספר", "לחם / ים", "כיסא / דג", "שולחן / לימון"),
                correctOption = "לחם / ים",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_008",
                questionText = "איזה זוג מתחרז?",
                options = listOf("תוף / סוף", "מטרייה / תפוח", "אבא / נעל", "קופסה / רכבת"),
                correctOption = "תוף / סוף",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_009",
                questionText = "איזה זוג מתחרז?",
                options = listOf("נעל / כוס", "גדר / חדר", "דלת / בובה", "כפית / תפוח"),
                correctOption = "גדר / חדר",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_010",
                questionText = "איזה זוג מתחרז?",
                options = listOf("גלידה / דג", "קוף / סוף", "מיטה / חלון", "כדור / סוס"),
                correctOption = "קוף / סוף",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_011",
                questionText = "איזה זוג מתחרז?",
                options = listOf("רימון / לימון", "חמור / תפוח", "נמלה / כוס", "דבש / מיטה"),
                correctOption = "רימון / לימון",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_012",
                questionText = "איזה זוג מתחרז?",
                options = listOf("פיל / חלב", "פרפר / ספר", "אוטו / חדר", "גזר / נעל"),
                correctOption = "פרפר / ספר",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_013",
                questionText = "איזה זוג מתחרז?",
                options = listOf("כדור / סידור", "חדר / נר", "ים / דג", "שמש / חלון"),
                correctOption = "כדור / סידור",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_014",
                questionText = "איזה זוג מתחרז?",
                options = listOf("כפית / חלב", "נמלה / קופסה", "תינוק / חילוק", "דלת / דג"),
                correctOption = "תינוק / חילוק",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_015",
                questionText = "איזה זוג מתחרז?",
                options = listOf("חלון / בלון", "כובע / רכבת", "שולחן / תפוח", "אבא / מיטה"),
                correctOption = "חלון / בלון",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
        )
}

