package com.tal.hebrewdino.ui.domain

object WordChallengeRepository {
    val letterRecognitionHebrewChapter1: List<WordChallenge> =
        listOf(
            WordChallenge(
                id = "ltr_001",
                questionText = "א",
                options = listOf("א", "מ", "ל", "ס"),
                correctOption = "א",
                challengeType = ChallengeType.LETTER_RECOGNITION,
                category = "זיהוי אות",
            ),
            WordChallenge(
                id = "ltr_002",
                questionText = "מ",
                options = listOf("א", "מ", "ל", "ס"),
                correctOption = "מ",
                challengeType = ChallengeType.LETTER_RECOGNITION,
                category = "זיהוי אות",
            ),
            WordChallenge(
                id = "ltr_003",
                questionText = "ל",
                options = listOf("א", "מ", "ל", "ס"),
                correctOption = "ל",
                challengeType = ChallengeType.LETTER_RECOGNITION,
                category = "זיהוי אות",
            ),
            WordChallenge(
                id = "ltr_004",
                questionText = "ס",
                options = listOf("א", "מ", "ל", "ס"),
                correctOption = "ס",
                challengeType = ChallengeType.LETTER_RECOGNITION,
                category = "זיהוי אות",
            ),
        )

    val phonemicIsolationHebrewChapter1Station2: List<WordChallenge> =
        listOf(
            WordChallenge(
                id = "ph_001",
                questionText = "א",
                options = listOf("א", "מ", "ל", "ס"),
                correctOption = "א",
                challengeType = ChallengeType.PHONEMIC_ISOLATION,
                category = "בידוד צליל",
            ),
            WordChallenge(
                id = "ph_002",
                questionText = "מ",
                options = listOf("א", "מ", "ל", "ס"),
                correctOption = "מ",
                challengeType = ChallengeType.PHONEMIC_ISOLATION,
                category = "בידוד צליל",
            ),
            WordChallenge(
                id = "ph_003",
                questionText = "ל",
                options = listOf("א", "מ", "ל", "ס"),
                correctOption = "ל",
                challengeType = ChallengeType.PHONEMIC_ISOLATION,
                category = "בידוד צליל",
            ),
            WordChallenge(
                id = "ph_004",
                questionText = "ס",
                options = listOf("א", "מ", "ל", "ס"),
                correctOption = "ס",
                challengeType = ChallengeType.PHONEMIC_ISOLATION,
                category = "בידוד צליל",
            ),
        )

    val oddOneOutHebrew: List<WordChallenge> =
        listOf(
            WordChallenge(
                id = "odd_001",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ח\".",
                options = listOf("חמור", "חזיר", "חלב", "מספריים"),
                correctOption = "מספריים",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_002",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"כ\".",
                options = listOf("כדור", "כיסא", "כפית", "תינוק"),
                correctOption = "תינוק",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_003",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ב\".",
                options = listOf("בלון", "בובה", "בית", "דג"),
                correctOption = "דג",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_004",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ד\".",
                options = listOf("דג", "דלת", "דבש", "חתול"),
                correctOption = "חתול",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_005",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"מ\".",
                options = listOf("מכונית", "מיטה", "מלפפון", "סוס"),
                correctOption = "סוס",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_006",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ס\".",
                options = listOf("סוכר", "סנדל", "סוס", "כדור"),
                correctOption = "כדור",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_007",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ש\".",
                options = listOf("שמש", "שוקו", "שולחן", "אבטיח"),
                correctOption = "אבטיח",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_008",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ר\".",
                options = listOf("רגל", "רכבת", "רימון", "בקבוק"),
                correctOption = "בקבוק",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_009",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"א\".",
                options = listOf("אוטו", "אבא", "אוכל", "מדורה"),
                correctOption = "מדורה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_010",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ל\".",
                options = listOf("לב", "לימון", "לחם", "מטרייה"),
                correctOption = "מטרייה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_011",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"פ\".",
                options = listOf("פרפר", "פיל", "פיצה", "גדר"),
                correctOption = "גדר",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_012",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"נ\".",
                options = listOf("נמלה", "נעל", "נר", "גלידה"),
                correctOption = "גלידה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_013",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ת\".",
                options = listOf("תוף", "תפוח", "תינוק", "כורסה"),
                correctOption = "כורסה",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_014",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ק\".",
                options = listOf("קוף", "קיץ", "קופסה", "ממתק"),
                correctOption = "ממתק",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
            WordChallenge(
                id = "odd_015",
                questionText = "איזו מילה יוצאת דופן? שלוש מילים מתחילות ב\"ג\".",
                options = listOf("גזר", "גדר", "גרב", "חלון"),
                correctOption = "חלון",
                challengeType = ChallengeType.ODD_ONE_OUT,
                category = "צליל פתיחה",
            ),
        )

    val rhymesHebrew: List<WordChallenge> =
        listOf(
            WordChallenge(
                id = "rhyme_001",
                questionText = "בלון",
                options = listOf("חלון", "חתול", "כיסא", "סוס"),
                correctOption = "חלון",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_002",
                questionText = "דבש",
                options = listOf("יבש", "כובע", "רכבת", "לב"),
                correctOption = "יבש",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_003",
                questionText = "בית",
                options = listOf("זית", "אוטו", "דלת", "ספר"),
                correctOption = "זית",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_004",
                questionText = "חתול",
                options = listOf("כחול", "בלון", "כיסא", "דג"),
                correctOption = "כחול",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_005",
                questionText = "ציפור",
                options = listOf("סיפור", "חתול", "דבש", "חלון"),
                correctOption = "סיפור",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_006",
                questionText = "דג",
                options = listOf("חג", "בובה", "גזר", "כובע"),
                correctOption = "חג",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_007",
                questionText = "דוב",
                options = listOf("טוב", "חלון", "כדור", "תפוח"),
                correctOption = "טוב",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_008",
                questionText = "תוף",
                options = listOf("סוף", "תפוח", "נעל", "רכבת"),
                correctOption = "סוף",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_009",
                questionText = "גדר",
                options = listOf("חדר", "כוס", "בובה", "תפוח"),
                correctOption = "חדר",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_010",
                questionText = "שמש",
                options = listOf("חמש", "כדור", "בלון", "כיסא"),
                correctOption = "חמש",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_011",
                questionText = "רימון",
                options = listOf("לימון", "תפוח", "כוס", "מיטה"),
                correctOption = "לימון",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_012",
                questionText = "מיטה",
                options = listOf("חיטה", "חלון", "כדור", "כיסא"),
                correctOption = "חיטה",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_013",
                questionText = "כדור",
                options = listOf("סידור", "נר", "דג", "חלון"),
                correctOption = "סידור",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_014",
                questionText = "עכבר",
                options = listOf("מדבר", "בלון", "חלב", "ספר"),
                correctOption = "מדבר",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
            WordChallenge(
                id = "rhyme_015",
                questionText = "חלון",
                options = listOf("בלון", "כובע", "תפוח", "מיטה"),
                correctOption = "בלון",
                challengeType = ChallengeType.RHYME,
                category = "חריזה",
            ),
        )
}
