package com.tal.hebrewdino.ui

/** Central route strings for navigation (used from screens and [AppNav]). */
object NavRoutes {
    const val Chapters = "chapters"
    const val StoryIntro = "story_intro"
    const val ChapterLettersIntro = "chapter_letters_intro"
    const val Journey = "journey"
    /** Episode 1 finale: return to journey, walk to egg, then show outro. */
    const val JourneyEndWalk = "journey_end_walk"
    const val Level = "level"
    const val Ch2Intro = "ch2_intro"
    const val Ch2Letters = "ch2_letters"
    const val Ch2Journey = "ch2_journey"
    const val Ch2Level = "ch2_level"
    const val Reward = "reward"
    const val Ch2Reward = "ch2_reward"
    const val Ch1MidBoost = "ch1_mid_boost"
    const val Ch2MidBoost = "ch2_mid_boost"
    const val Ch3MidBoost = "ch3_mid_boost"
    const val Ch4MidBoost = "ch4_mid_boost"
    const val Ch5MidBoost = "ch5_mid_boost"
    const val Ch3Intro = "ch3_intro"
    const val Ch3Letters = "ch3_letters"
    const val Ch3Journey = "ch3_journey"
    const val Ch3Level = "ch3_level"
    const val Ch3Reward = "ch3_reward"
    const val Ch2StoryOutro = "ch2_story_outro"
    const val Ch3StoryOutro = "ch3_story_outro"
    const val Ch4Intro = "ch4_intro"
    const val Ch4Letters = "ch4_letters"
    const val Ch4Journey = "ch4_journey"
    const val Ch4Level = "ch4_level"
    const val Ch4Reward = "ch4_reward"
    const val Ch4Outro = "ch4_outro"
    const val Ch5Intro = "ch5_intro"
    const val Ch5Letters = "ch5_letters"
    const val Ch5Journey = "ch5_journey"
    const val Ch5Level = "ch5_level"
    const val Ch5Reward = "ch5_reward"
    const val Ch5Outro = "ch5_outro"
    const val Ch6Intro = "ch6_intro"
    const val Ch6Letters = "ch6_letters"
    const val Ch6Journey = "ch6_journey"
    const val Ch6Level = "ch6_level"
    const val Ch6Reward = "ch6_reward"
    const val Ch6Outro = "ch6_outro"
    const val StoryOutro = "story_outro"
    const val Settings = "settings"
}
